on: push
jobs:
  ExampleWorkflow:
    runs-on: windows-latest
    defaults:
      run: 
        working-directory: ./Actions
    steps:
    - run: echo "Example Workflow Starting"
    - run: check-uproject.bat
