name: Example Workflow

on: 
  pull_request:
    types: [opened]

permissions: write-all

jobs:
  ExampleWorkflow:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Start Message
        run: echo "Example Workflow Starting"

      - name: Run check-uproject.bat
        run: Actions\check-uproject.bat

      - name: The job has failed
        if: ${{ failure() }}
        run: gh pr close ${{github.event.pull_request.number}} --comment "Could Not Find *.uproject file"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
